import { Inter } from 'next/font/google'
import './globals.css'
import Advice from '../src/advice'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <layout lang="en">
      <Advice />
      <main>{children}</main>

    </layout>
  )
}
